TwitterBot.Web/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using TwitterBot.Core;
using TwitterBot.Core.IRepository;
using TwitterBot.Core.Models;
using TwitterBot.Core.NoDbModels;
using TwitterBot.Core.ViewModel;
using TwitterBot.DataAccess.Repository;

namespace TwitterBot.Web.Areas.Admin.Controllers
{
    [Area(nameof(Admin))]
    [Authorize(Roles = Shared.Role_Admin)]
    public class UsersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(IUnitOfWork unitOfWork, 
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            _unitOfWork = unitOfWork;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        public ActionResult<IEnumerable<UserVM>> Index()
        {
            var users = _unitOfWork.User.GetUserVMs();
            return View(users);
        }
        public async Task<ActionResult<UserVM>> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var userVM = new UserVM 
            { 
                Id = user.Id, 
                Name = user.UserName, 
                IsActive = user.IsActive,
                Role = _unitOfWork.User.GetRoleName(id),
                RoleList =  _roleManager.Roles.Select(r => r.Name).Select(r => new SelectListItem()
                {
                    Text = r,
                    Value = r
                }),
            };
            return View(userVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult<UserVM> Edit(UserVM userVM)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.User.Update(userVM);
                _unitOfWork.SaveChanges();

                TempData["success"] = "User Updated successfully";
                return RedirectToAction(nameof(Index));
            }
            return View(userVM);
        }
        [HttpDelete]
        public IActionResult Delete(string? id)
        {
            var userfromDb = _unitOfWork.User.GetFirstOrDefualt(u => u.Id == id);
            if (userfromDb == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }


            _unitOfWork.User.Remove(userfromDb);
            _unitOfWork.SaveChanges();
            return Json(new { success = true, message = "User deleted successfully" });
        }
    }
}

TwitterBot.Web/Areas/NewsReviewer/Controllers/NewsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using TwitterBot.Core;
using TwitterBot.Core.IRepository;
using TwitterBot.Core.IServices;
using TwitterBot.Core.NoDbModels;

namespace TwitterBot.Web.Areas.NewsReviewer.Controllers
{
    [Area(nameof(NewsReviewer))]
    [Authorize(Roles = Shared.Role_NewsReviewer)]
    public class NewsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly INewsService _newsService;
        private readonly IChatGPTService _chatGPT;
        private readonly ITwitterHandlerService _twitterHandler;

        public NewsController(IUnitOfWork unitOfWork,
            INewsService newsService,
            IChatGPTService chatGPT,
            ITwitterHandlerService twitterHandler)
        {
            _unitOfWork = unitOfWork;
            _newsService = newsService;
            _chatGPT = chatGPT;
            _twitterHandler = twitterHandler;
        }
        public IActionResult Index()
        {
            var news = _newsService.GetAllNewsFromDb(c => !c.IsExpired);
			return View(news);
        }
        public IActionResult Paraphrasing(int id)
        {
            var news = _unitOfWork.News.GetFirstOrDefualt(n => n.Id == id);
            if (news != null)
            {
                var done = _chatGPT.SendChatMessage(news).Result;
            }
            _unitOfWork.SaveChanges();
            return Redirect(nameof(Index));
        }
        public IActionResult PostOnTwitter(int id)
        {
            var news = _unitOfWork.News.GetFirstOrDefualt(n => n.Id == id);
            if (news != null)
            {
                var done = _twitterHandler.PostTweet(new PostTweetRequestDto
                {
                    Text = news.ParaphrasdNews ?? news.OriganalNews,
                }).Result;
                if (done)
                {
                    news.IsApproved = true;
                    news.IsExpired = true;
                    news.DecisionById = User.FindFirstValue(ClaimTypes.NameIdentifier);
                    news.DecisionTime = DateTime.Now;
                }
                _unitOfWork.SaveChanges();
            }
            return Redirect(nameof(Index));
        }
        public IActionResult Rejected(int id)
        {
            if(id == 0) return RedirectToAction("Index");
            var news = _unitOfWork.News.GetFirstOrDefualt(n => n.Id == id);
            if (news != null)
            {
                news.IsExpired = true;
                _unitOfWork.SaveChanges();
            }
            return Redirect(nameof(Index));
        }
    }
}

TwitterBot.Web/Views/Shared/_Layout.cshtml
@using TwitterBot.Core
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Twitter Bot</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TwitterBot.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary text-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Twitter Bot </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole(Shared.Role_NewsReviewer) )
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        @if (User.IsInRole(Shared.Role_NewsReviewer))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="NewsReviewer" asp-controller="News" asp-action="Index">News</a>
                            </li>
                          
                        }
                        @if (User.IsInRole(Shared.Role_Admin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Admin" asp-controller="Users" asp-action="Index">User Managmet</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-primary">
        <div class="container text-white bg-primary">
            &copy; 2024 - TwitterBot.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/1.11.2/js/jquery.dataTables.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>